name: Upload to PyPI
on:
  push:
    tags:
      - "1.*"

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.repository == 'alorenzo175/solarforecastarbiter-core'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch_depth: 0
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Build
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools wheel
          python setup.py sdist bdist_wheel
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.3.1
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
          repository_url: https://test.pypi.org/legacy/
